### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Heath3827** [benjojo/de-ip-hdmi#13]
How do I use your tool to capture the video and display in VLC? Your blog says it is possible but there are no examples to show how to do it.

**Comment by benjojo** [comment]
`./de-ip-hdmi -interface XXX -raw | ffplay -`

replace ffplay with vlc if you don't have ffmpeg installed, but you will likely need ffmpeg anyway for anything that isnt -raw mode

**Comment by Heath3827** [comment]
No joy:
________________________________________________

sudo de-ip-hdmi -interface wlo0 -raw | ffplay -
[sudo] password for andrew: ffplay version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2003-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0   
pipe:: Invalid data found when processing input
____________________________________________________

sudo de-ip-hdmi -interface wlo0 -raw | vlc
VLC media player 3.0.4 Vetinari (revision 3.0.4-0-gf615db6332)
[sudo] password for andrew: [000055d37c55b570] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[000055d37c5eb660] main playlist: playlist is empty

QObject::~QObject: Timers cannot be stopped from another thread

**Comment by benjojo** [comment]
You are using a wireless interface there, You should connect the ethernet directly to the system for best results, otherwise MAC spoofing etc will not work

**Comment by Heath3827** [comment]
Same results on wired.

**Comment by benjojo** [comment]
Are you sure you entered your sudo password? I've been tripped up by that a
few times...

**Comment by Heath3827** [comment]
Yes, and am not getting wrong password errors. If it helps, I installed the .deb build. IP if the sender unit is currently 192.168.1.9.

**Comment by benjojo** [comment]
Hmph. I think the version of the sender you have is not the one supported
by this software. Since V2 devices do not grab a IP address.

Can you look at the PCB for what version the board is? This software only
supports V2 devices, and they are much less common these days

**Comment by Heath3827** [comment]
The box has a V3 legend but the board looks to have a Ver1.0 marking. Interior looks quite different to the photo on your blog page.

![20190623_013353](https://user-images.githubusercontent.com/31277724/59967095-30ce5500-9558-11e9-80b2-698094f80b1c.jpg)
![20190623_013418](https://user-images.githubusercontent.com/31277724/59967096-3166eb80-9558-11e9-925f-9c1caefb51e9.jpg)
![20190623_013438](https://user-images.githubusercontent.com/31277724/59967097-3166eb80-9558-11e9-977e-48a1ef11c73e.jpg)
![20190623_013444](https://user-images.githubusercontent.com/31277724/59967098-31ff8200-9558-11e9-9adb-94d0ff57a278.jpg)

**Comment by benjojo** [comment]
That board is not compatible with this software, sorry!

**Comment by Heath3827** [comment]
Any ideas on an alternative?

**Comment by benjojo** [comment]
You want this: https://blog.danman.eu/new-version-of-lenkeng-hdmi-over-ip-extender-lkv373a/
